rlw: prevent infinite loop when wine is found, but not wineboot/wineserver

diff --git a/rlw b/rlw
--- a/rlw
+++ b/rlw
@@ -198,10 +198,15 @@ winechooser () {
 			# Here, we will literally save '$(which wine)' as the path
 			# so it changes dynamically and isn't immediately evaluated.
 			winebin='$(which wine)'
-			if [[ ! -x "$(eval "echo $winebin")" ]]; then
-				spawndialog error 'Missing dependencies! Please install wine somewhere in $PATH, or select a custom path instead.'
-				exit 1
-			fi;;
+			real_winebin="$(eval "echo $winebin")"
+			winebootbin="$(dirname $real_winebin)/wineboot"
+			wineserverbin="$(dirname $real_winebin)/wineserver"
+			for x in "$real_winebin" "$winebootbin" "$wineserverbin"; do
+				if [[ ! -x "$x" ]]; then
+					spawndialog error "Missing dependencies! Please install wine somewhere in "'$PATH'", or select a custom path instead.\nDetails: Could not find $(basename $x) at $x. Are you sure a copy is installed there?"
+					exit 1
+				fi
+			done;;
 		*)
 			winebin="$sel"
 	esac
