Many changes Improve syntax Choose wine version before initial prefix generation Some other things I forgot

diff --git a/rlw b/rlw
--- a/rlw
+++ b/rlw
@@ -89,7 +89,7 @@ rwinetricks () {
 	}
 	$winetricksbin "$@"
 	[[ "$?" = "0" ]] || {
-		spawndialog error "winetricks failed. \nSee terminal for details. (exit code $?"
+		spawndialog error "winetricks failed. \nSee terminal for details. (exit code $?)"
 		exit $?
 	}
 	printf '%b\n' " > end rwinetricks ()\n---"
@@ -161,13 +161,13 @@ wineinitialize () {
 	# Evaluate the Wine path selection, and base the wineboot/wineserver
 	# paths off that.
 	source "$HOME/.rlw/wine_choice"
-	winebootbin="$(dirname $WINE)/wineboot"
-	wineserverbin="$(dirname $WINE)/wineserver"
+	winebootbin="$(dirname "$WINE")/wineboot"
+	wineserverbin="$(dirname "$WINE")/wineserver"
 	for x in "$WINE" "$winebootbin" "$wineserverbin"; do
 		if [[ -x "$x" ]]; then
-			printf "%b\n" "$(basename $x) path set to $x"
+			printf "%b\n" "$(basename "$x") path set to $x"
 		else
-			spawndialog error "Could not find $(basename $x) at $x. Are you sure a copy is installed there?"
+			spawndialog error "Could not find $(basename "$x") at $x. Are you sure a copy is installed there?"
 			winechooser
 			break
 		fi
@@ -200,13 +200,13 @@ winechooser () {
 		'Automatic detection (via $PATH)')
 			# Here, we will literally save '$(which wine)' as the path
 			# so it changes dynamically and isn't immediately evaluated.
-			WINE='$(which wine)'
+			WINE="$(which wine)"
 			real_wine="$(eval "echo $WINE")"
-			winebootbin="$(dirname $real_wine)/wineboot"
-			wineserverbin="$(dirname $real_wine)/wineserver"
+			winebootbin="$(dirname "$real_wine")/wineboot"
+			wineserverbin="$(dirname "$real_wine")/wineserver"
 			for x in "$real_wine" "$winebootbin" "$wineserverbin"; do
 				if [[ ! -x "$x" ]]; then
-					spawndialog error "Missing dependencies! Please install wine somewhere in "'$PATH'", or select a custom path instead.\nDetails: Could not find $(basename $x) at $x. Are you sure a copy is installed there?"
+					spawndialog error "Missing dependencies! Please install wine somewhere in "'$PATH'", or select a custom path instead.\nDetails: Could not find $(basename "$x") at $x. Are you sure a copy is installed there?"
 					exit 1
 				fi
 			done;;
@@ -229,13 +229,8 @@ winechooser () {
 
 main () {
 	printf '%b\n' " > begin main ()\n---"
-	rm -f $HOME/Desktop/ROBLOX*.lnk
+	rm -f "$HOME/Desktop/ROBLOX*.lnk"
 	rm -rf "$HOME/.local/share/applications/wine/Programs/Roblox"
-	if [[ ! -f "$HOME/.rlw/wine_choice" ]]; then
-		printf "%b\n" "No Wine path has been saved yet, starting winechooser..."
-		winechooser
-	fi
-	wineinitialize
 	sel=$(zenity \
 		--title="$rlwversionstring" \
 		--window-icon="$RBXICON" \
@@ -266,6 +261,7 @@ main () {
 		spawndialog question 'Are you sure you would like to reinstall?'
 		if [[ "$?" = "0" ]]; then
 			rm -rf "$HOME/.rlw"
+			$wineserverbin -k
 			rm -rf "$WINEPREFIX"
 			roblox-install; main
 		else
@@ -321,5 +317,12 @@ if [ "$(id -u)" == "0" ]; then
    spawndialog error "Roblox Linux Wrapper should not be ran with root permissions."
    exit 1
 fi
+
+# Make sure wine release is defined before continuing
+if [[ ! -f "$HOME/.rlw/wine_choice" ]]; then
+	printf "%b\n" "No Wine path has been saved yet, starting winechooser..."
+	winechooser
+fi
+wineinitialize
 
 roblox-install && main
