rlw: Fix winechooser / dependency checking logic

diff --git a/rlw b/rlw
--- a/rlw
+++ b/rlw
@@ -154,6 +154,27 @@ playerwrapper () {
 	printf '%b\n' " > end playerwrapper ()\n---"
 }
 
+wineinitialize () {
+	# Evaluate the Wine path selection, and base the wineboot/wineserver
+	# paths off that.
+	source "$HOME/.rlw/wine_choice"
+	winebootbin="$(dirname $winebin)/wineboot"
+	wineserverbin="$(dirname $winebin)/wineserver"
+	for x in "$winebin" "$winebootbin" "$wineserverbin"; do
+		if [[ -x "$x" ]]; then
+			printf "%b\n" "$(basename $x) path set to $x"
+		else
+			spawndialog error "Could not find $(basename $x) at $x. Are you sure a copy is installed there?"
+			winechooser
+			break
+		fi
+	done
+	[[ "$($winebin --version | sed 's/.*-//')" > "1.7.27" ]] || {
+		spawndialog error "Your copy of Wine is too old. Please install version 1.7.28 or greater.\n(expected 1.7.28, got $(wine --version | sed 's/.*-//'))"
+		exit 1
+	}
+}
+
 winechooser () {
 	sel=$(zenity \
 			--title "Wine Version Selection" \
@@ -175,8 +196,12 @@ winechooser () {
 					  --text "Enter custom Wine path:" --entry);;
 		'Automatic detection (via $PATH)')
 			# Here, we will literally save '$(which wine)' as the path
-			# so it changes dynamically and isn't immediately executed.
-			winebin='$(which wine)';;
+			# so it changes dynamically and isn't immediately evaluated.
+			winebin='$(which wine)'
+			if [[ ! -x "$(eval "echo $winebin")" ]]; then
+				spawndialog error 'Missing dependencies! Please install wine somewhere in $PATH, or select a custom path instead.'
+				exit 1
+			fi;;
 		*)
 			winebin="$sel"
 	esac
@@ -190,19 +215,8 @@ winechooser () {
 		printf "%b\n" "Saving Wine choice to ~/.rlw/wine_choice"
 		echo "winebin=$winebin" > "$HOME/.rlw/wine_choice"
 		mkdir -p "$HOME/.rlw/"
-		source "$HOME/.rlw/wine_choice"
-		winebootbin="$(dirname $winebin)/wineboot"
-		wineserverbin="$(dirname $winebin)/wineserver"
-		for x in "$winebin" "$winebootbin" "$wineserverbin"; do
-			if [[ -x "$x" ]]; then
-				printf "%b\n" "$(basename $x) path set to $x"
-			else
-				spawndialog error "Could not find $(basename $x) at $x. Are you sure a copy is installed there?"
-				winechooser
-				break
-			fi
-		done
 	fi
+	wineinitialize
 }
 
 main () {
@@ -213,6 +227,7 @@ main () {
 		printf "%b\n" "No Wine path has been saved yet, starting winechooser..."
 		winechooser
 	fi
+	wineinitialize
 	sel=$(zenity \
 		--title='Roblox Linux Wrapper '"$rlwversion"'' \
 		--window-icon="$RBXICON" \
@@ -294,10 +309,5 @@ if [ "$(id -u)" == "0" ]; then
    spawndialog error "Roblox Linux Wrapper should not be ran with root permissions."
    exit 1
 fi
-
-[[ "$(wine --version | sed 's/.*-//')" > "1.7.27" ]] || {
-	spawndialog error "Your copy of Wine is too old. Please install version 1.7.28 or greater.\n(expected 1.7.28, got $(wine --version | sed 's/.*-//'))"
-	exit 1
-}
 
 roblox-install && main
